// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: raftbasic.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurTerm       int64                  `protobuf:"varint,1,opt,name=CurTerm,proto3" json:"CurTerm,omitempty"`
	SefId         int64                  `protobuf:"varint,2,opt,name=SefId,proto3" json:"SefId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_raftbasic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftbasic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_raftbasic_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRequest) GetCurTerm() int64 {
	if x != nil {
		return x.CurTerm
	}
	return 0
}

func (x *VoteRequest) GetSefId() int64 {
	if x != nil {
		return x.SefId
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurTerm       int64                  `protobuf:"varint,1,opt,name=CurTerm,proto3" json:"CurTerm,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_raftbasic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftbasic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_raftbasic_proto_rawDescGZIP(), []int{1}
}

func (x *VoteResponse) GetCurTerm() int64 {
	if x != nil {
		return x.CurTerm
	}
	return 0
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurTerm       int64                  `protobuf:"varint,1,opt,name=CurTerm,proto3" json:"CurTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntryRequest) Reset() {
	*x = AppendEntryRequest{}
	mi := &file_raftbasic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntryRequest) ProtoMessage() {}

func (x *AppendEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftbasic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntryRequest.ProtoReflect.Descriptor instead.
func (*AppendEntryRequest) Descriptor() ([]byte, []int) {
	return file_raftbasic_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntryRequest) GetCurTerm() int64 {
	if x != nil {
		return x.CurTerm
	}
	return 0
}

type AppendEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntryResponse) Reset() {
	*x = AppendEntryResponse{}
	mi := &file_raftbasic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntryResponse) ProtoMessage() {}

func (x *AppendEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftbasic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntryResponse.ProtoReflect.Descriptor instead.
func (*AppendEntryResponse) Descriptor() ([]byte, []int) {
	return file_raftbasic_proto_rawDescGZIP(), []int{3}
}

var File_raftbasic_proto protoreflect.FileDescriptor

const file_raftbasic_proto_rawDesc = "" +
	"\n" +
	"\x0fraftbasic.proto\x12\x06raftpb\"=\n" +
	"\vVoteRequest\x12\x18\n" +
	"\aCurTerm\x18\x01 \x01(\x03R\aCurTerm\x12\x14\n" +
	"\x05SefId\x18\x02 \x01(\x03R\x05SefId\"J\n" +
	"\fVoteResponse\x12\x18\n" +
	"\aCurTerm\x18\x01 \x01(\x03R\aCurTerm\x12 \n" +
	"\vVoteGranted\x18\x02 \x01(\bR\vVoteGranted\".\n" +
	"\x12AppendEntryRequest\x12\x18\n" +
	"\aCurTerm\x18\x01 \x01(\x03R\aCurTerm\"\x15\n" +
	"\x13AppendEntryResponse2\x92\x01\n" +
	"\x0eMessageService\x128\n" +
	"\vRequestVote\x12\x13.raftpb.VoteRequest\x1a\x14.raftpb.VoteResponse\x12F\n" +
	"\vAppendEntry\x12\x1a.raftpb.AppendEntryRequest\x1a\x1b.raftpb.AppendEntryResponseB\vZ\t../raftpbb\x06proto3"

var (
	file_raftbasic_proto_rawDescOnce sync.Once
	file_raftbasic_proto_rawDescData []byte
)

func file_raftbasic_proto_rawDescGZIP() []byte {
	file_raftbasic_proto_rawDescOnce.Do(func() {
		file_raftbasic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftbasic_proto_rawDesc), len(file_raftbasic_proto_rawDesc)))
	})
	return file_raftbasic_proto_rawDescData
}

var file_raftbasic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_raftbasic_proto_goTypes = []any{
	(*VoteRequest)(nil),         // 0: raftpb.VoteRequest
	(*VoteResponse)(nil),        // 1: raftpb.VoteResponse
	(*AppendEntryRequest)(nil),  // 2: raftpb.AppendEntryRequest
	(*AppendEntryResponse)(nil), // 3: raftpb.AppendEntryResponse
}
var file_raftbasic_proto_depIdxs = []int32{
	0, // 0: raftpb.MessageService.RequestVote:input_type -> raftpb.VoteRequest
	2, // 1: raftpb.MessageService.AppendEntry:input_type -> raftpb.AppendEntryRequest
	1, // 2: raftpb.MessageService.RequestVote:output_type -> raftpb.VoteResponse
	3, // 3: raftpb.MessageService.AppendEntry:output_type -> raftpb.AppendEntryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raftbasic_proto_init() }
func file_raftbasic_proto_init() {
	if File_raftbasic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftbasic_proto_rawDesc), len(file_raftbasic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raftbasic_proto_goTypes,
		DependencyIndexes: file_raftbasic_proto_depIdxs,
		MessageInfos:      file_raftbasic_proto_msgTypes,
	}.Build()
	File_raftbasic_proto = out.File
	file_raftbasic_proto_goTypes = nil
	file_raftbasic_proto_depIdxs = nil
}
